apiVersion: v1      
data: 
  kubeconfig: |
{{- range $index, $secret := (lookup "v1" "Secret" "gloo-system" "").items }}
  {{- if (hasPrefix "gloo-fed-token-" $secret.metadata.name) }}
    {{- if not (index $secret.metadata.annotations "kubernetes.io/created-by") }}
      {{ (include "gloo-fed-local.kubeconfig" $secret) | b64enc }}
    {{- end }}
  {{- end }}
{{- end }}
kind: Secret
type: solo.io/kubeconfig
metadata:
  name: gloo-fed-cluster-local
  namespace: gloo-system
